### ISSUE TITLE
I'm curious if it's correct that there are no crashes with the code in the example

### ISSUE THREAD

**Issue by howl201** [Metalnem/sharpfuzz-samples#4]
I'm trying to run the example to check if your sharpfuzz is working properly, and it seems to run without issues. However, I can't seem to find any crashes or hangs. Even with deserialization, it appears that crashes or hangs should be detected, given what you have uploaded as an example. But when I try it, I can't find any results. I've been running it for up to 5 days, and it's been 3 days without discovering any new paths. I'm wondering if this is normal or if I'm doing something wrong.

If desired, I can run it for about a day and provide a screenshot since I missed taking one.

**Comment by Metalnem** [comment]
Hi @howl201! Which example have you been running? There are no guarantees that SharpFuzz will find crashes or hangs, especially if the library is well tested or if it has been fuzzed before.

And yes, screenshot will be useful to determine if the fuzzing was set up correctly.

**Comment by howl201** [comment]
The first screenshot is from running the first corresponding command in this repository example:
scripts/fuzz.ps1 src/ProtobufNet/ProtobufNet.Fuzz.csproj `
    -i src/ProtobufNet/Testcases
I conducted the test using the fuzz.ps1 script with the -d option when running AFL. This resulted in a low depth but broader search, quickly exploring multiple paths. While the "cycle done" count increased rapidly, I couldn't find any crashes or hangs. Since the "cycle done" count didn't continue to rise, I decided to stop.
<img width="306" alt="image" src="https://github.com/Metalnem/sharpfuzz-samples/assets/104803826/2c3409c8-044d-43f8-b737-ae973e64382c">


The second screenshot is from running the second corresponding command in the repository example:
scripts/fuzz.ps1 src/Markdig/Markdig.Fuzz.csproj `
    -i src/Markdig/Testcases `
    -x dictionaries/markdown.dict
I tested using the fuzz.ps1 script as provided here. Again, I couldn't find any crashes or hangs. Notably, the fuzzing speed seemed relatively slow in this case.
<img width="490" alt="image" src="https://github.com/Metalnem/sharpfuzz-samples/assets/104803826/d3b3628f-6caa-4134-8b27-75b5aa215cdf">


Finally, the third screenshot is from running the version without the -d option in fuzz.ps1, similar to the first run. I executed it today, and while the execution time was relatively short, I still couldn't find any crashes or hangs.
<img width="529" alt="image" src="https://github.com/Metalnem/sharpfuzz-samples/assets/104803826/9749e752-a678-4f2d-923a-fc066c94d491">

I'm worried that I haven't been able to visually confirm any crashes to verify if the fuzzer is working correctly. I'm wondering if I might be doing something wrong, or if the examples provided here simply don't result in any discoveries. Or perhaps it's just a matter of bad luck.

Thank you sincerely for brainstorming this with me.

**Comment by Metalnem** [comment]
Hi @howl201,

It seems that you are doing everything right. The number of total paths is high in all cases, showing that you are correctly exploring many paths.

The biggest problem with using the samples from this repo is that I already used all of them to find a lot of bugs :) Here are the bugs that I found in Markdig using SharpFuzz (the full list of bugs is available [here]( https://github.com/Metalnem/sharpfuzz#trophies)):

<img width="784" alt="Screen Shot 2023-09-26 at 10 10 42 PM" src="https://github.com/Metalnem/sharpfuzz-samples/assets/2280548/a8e3ad4b-110b-44de-a5c0-b16a47da96c8">

You probably need to fuzz some library that was not fuzzed before. Here is one suggestion what you might try: https://github.com/Cysharp/MemoryPack.

**Comment by howl201** [comment]
I sincerely thank you for your kind response. I was too busy last week and couldn't properly test the MemoryPack you suggested with SharpFuzz, but I will let you know the results as soon as they are available. Thank you once again for your assistance.
